{{- if and .Values.modelApiKeys (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemo-guardrails.secretName" . }}
  labels:
    {{- include "nemo-guardrails.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.modelApiKeys }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
